"""
Script Name : fcc_091_ai_detector.py
Description : AI Detector
Author      : @tonybnya

Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

- It contains two or more dashes (-).
- It contains two or more sets of parenthesis (()). Text can be within the parenthesis.
- It contains three or more words with 7 or more letters.
- Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.

If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".
"""


def get_special_chars(text: str) -> tuple[int]:
    dashes: int = 0
    o_brackets: int = 0
    c_brackets: int = 0

    for c in text:
        if c == '-':
            dashes += 1
        elif c == '(':
            o_brackets += 1
        elif c == ')':
            c_brackets += 1
    return dashes, o_brackets, c_brackets


def count_alpha(word: str) -> int:
    alpha: int = 0
    for c in word:
        if c.isalpha():
            alpha += 1
    return alpha


def count_words_7plus(text: str) -> int:
    words: list[str] = text.split()
    words_7plus: int = 0
    for word in words:
        if count_alpha(word) >= 7:
            words_7plus += 1
    return words_7plus


def detect_ai(text: str) -> str:
    dashes, o_brackets, c_brackets = get_special_chars(text)
    if dashes >= 2:
        return 'AI'
    if o_brackets >= 2 and c_brackets >= 2:
        return 'AI'
    if count_words_7plus(text) >= 3:
        return 'AI'
    return 'Human'
